enyo.depends(
	"Spinn/depends.js",
	"javaScripts/LocTaggerUtils.js",
	"LocationDetails/depends.js",
	"addLocation/depends.js",
	"ManualLocationDialog/depends.js",
	"FileIO/depends.js",
	"app/components/database-enyo.js",
	"app/components/locations-model.js",
	"stylesheets/style.css",
	"app/LocationTagger.js"
);